---
site_name: "dismech schema docs"
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: indigo
  features:
    - content.tabs.link
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.suggest
  font: false

# for adding extra css/js see https://www.mkdocs.org/user-guide/customizing-your-theme/
extra_css:
  - stylesheets/dismech-mkdocs.css

plugins:
  - search:
      lang: en
      separator: '[\s\-]+'
  - mknotebooks:
      execute: false
  - mermaid2:
      version: 11.4.1
  # TODO rebuild docs on schema change (https://github.com/dalito/linkml-project-copier/issues/39)
  # - gen-files:
  #     scripts:
  #       - gen_pages.py  # or any other name or path

watch:
  - src/dismech/schema

validation:
  nav:
    omitted_files: ignore

nav:
  - Home: index.md
  - Schema Reference: schema/index.md

exclude_docs: |
  /templates-linkml/
  /about.md
  /elements/

site_url: https://dismech.monarchinitiative.org/elements/
site_dir: elements
repo_url: https://github.com/monarch-initiative/dismech

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
